import { Metadata } from "next";
import "./global.css";
import Nav from "@/components/NavBar/Nav";

export const metadata: Metadata = {
  title: "Next.js Clinic Management System",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

type Props = {
  children: React.ReactNode;
  login: React.ReactNode;
};

export default function RootLayout({ children, login }: Props) {
  const isLoggedIn = false;
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        {isLoggedIn && login}
      </body>
    </html>
  );
}
